version: '2'
linters:
  default: none
  enable:
    - bodyclose
    # - depguard
    - gocritic
    - govet
    - ineffassign
    - nolintlint
    - staticcheck
    - unconvert
    - unused
  settings:
    forbidigo:
      forbid:
        - pattern: fmt\.Errorf
    gocritic:
      disabled-checks:
        - appendAssign
        - assignOp
        - commentFormatting
        - deprecatedComment
        - exitAfterDefer
        - ifElseChain
        - singleCaseSwitch
    govet:
      disable:
        - composites
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - bodyclose
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
