jobs:
  checkPipeline:
    name: render-CI-pipeline
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v4'
      - uses: jdx/mise-action@v2
      - name: Check that the CI pipeline definition is up-to-date with the dhall configuration
        run: ci/check-rendered-pipeline-up-to-date.sh

  golangciLint:
    name: golangci-lint
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v4'
      - uses: jdx/mise-action@v2
      - name: 'golangci-lint (.)'
        uses: 'golangci/golangci-lint-action@v8'
        with:
          working-directory: '.'

  prettier:
    name: Prettier formatting
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v4'
      - uses: jdx/mise-action@v2
      - name: Check Prettier formatting
        run: ci/check-prettier.sh

  shellcheck:
    name: shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v4'
      - uses: jdx/mise-action@v2
      - name: Lint shell scripts
        run: just shellcheck

  shfmt:
    name: shfmt
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v4'
      - uses: jdx/mise-action@v2
      - name: Check that scripts are formatted consistently
        run: ci/check-shfmt.sh

  wasmBuild:
    name: Build WASM
    runs-on: ubuntu-22.04
    steps:
      - uses: 'actions/checkout@v4'
      - uses: jdx/mise-action@v2
      - env:
          CI: 'true'
        name: Build WASM binary
        run: just build-wasm
name: CI
on:
  push: {}
